Name:           ros-hydro-pr2-motor-diagnostic-tool
Version:        1.0.7
Release:        0%{?dist}
Summary:        ROS pr2_motor_diagnostic_tool package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_motor_diagnostic_tool
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-ethercat-hardware
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-pr2-controller-interface
Requires:       ros-hydro-pr2-mechanism-model
Requires:       ros-hydro-pr2-mechanism-msgs
Requires:       ros-hydro-rospy
Requires:       ros-hydro-rqt-gui
Requires:       ros-hydro-rqt-gui-py
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-ethercat-hardware
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-pr2-controller-interface
BuildRequires:  ros-hydro-pr2-mechanism-model
BuildRequires:  ros-hydro-pr2-mechanism-msgs
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rqt-gui
BuildRequires:  ros-hydro-rqt-gui-py

%description
pr2_motor_diagnostic_tool

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Dec 02 2014 Dash <dash@clearpathrobotics.com> - 1.0.7-0
- Autogenerated by Bloom

* Fri Nov 28 2014 Dash <dash@clearpathrobotics.com> - 1.0.6-0
- Autogenerated by Bloom

